/**
 * Curated Bandcamp album URLs for Discover when `/tag/*` hub HTML no longer
 * embeds album links (Vue SPA). Each URL must be a public album with
 * `data-tralbum` + `mp3-128` on the page (see {@link bandcampService}).
 */
export const BANDCAMP_DISCOVER_ALBUM_SEEDS: readonly string[] = [
  'https://nilsfrahm.bandcamp.com/album/all-melody',
  'https://tycho.bandcamp.com/album/awake',
  'https://floatingpoints.bandcamp.com/album/crush',
  'https://caribouband.bandcamp.com/album/our-love',
  'https://khruangbin.bandcamp.com/album/the-universe-smiles-upon-you',
  'https://jonhopkins.bandcamp.com/album/immunity',
  'https://bicep.bandcamp.com/album/bicep',
  'https://overmono.bandcamp.com/album/good-lies',
  'https://flyinglotus.bandcamp.com/album/yasuke',
  'https://teebs.bandcamp.com/album/ardour',
  'https://teebs.bandcamp.com/album/collections-01',
  'https://emancipator.bandcamp.com/album/dusk-to-dawn',
  'https://cattledecapitation.bandcamp.com/album/death-atlas',
  'https://mfdoom.bandcamp.com/album/mm-food',
  'https://jpegmafia.bandcamp.com/album/all-my-heroes-are-cornballs',
  'https://sunn.bandcamp.com/album/black-one',
  'https://chelseawolfe.bandcamp.com/album/pain-is-beauty',
  'https://maxcooper.bandcamp.com/album/one-hundred-billion-sparks',

  // ── Expanded pool (50) — same `data-tralbum` preview contract; HTTP-checked 200.
  'https://moderat.bandcamp.com/album/iii',
  'https://comtruise.bandcamp.com/album/in-decay',
  'https://fourtet.bandcamp.com/album/sixteen-oceans',
  'https://timhecker.bandcamp.com/album/ravedeath-1972',
  'https://machinedrum.bandcamp.com/album/vapor-city',
  'https://goldpanda.bandcamp.com/album/half-of-where-you-live',
  'https://lcdsoundsystem.bandcamp.com/album/american-dream',
  'https://toroymoi.bandcamp.com/album/outer-peace',
  'https://arca1000000.bandcamp.com/album/kick-ii',
  'https://oneohtrixpointnever.bandcamp.com/album/magic-oneohtrix-point-never',
  'https://objekt.bandcamp.com/album/cocoon-crush',
  'https://actress.bandcamp.com/album/azd',
  'https://rustie.bandcamp.com/album/glass-swords',
  'https://caribouband.bandcamp.com/album/suddenly',
  'https://caribouband.bandcamp.com/album/swim',
  'https://nilsfrahm.bandcamp.com/album/spaces',
  'https://nilsfrahm.bandcamp.com/album/felt',
  'https://nilsfrahm.bandcamp.com/album/solo',
  'https://tycho.bandcamp.com/album/weather',
  'https://tycho.bandcamp.com/album/epoch',
  'https://floatingpoints.bandcamp.com/album/promises',
  'https://bicep.bandcamp.com/album/isles',
  'https://jonhopkins.bandcamp.com/album/singularity',
  'https://khruangbin.bandcamp.com/album/mordechai',
  'https://khruangbin.bandcamp.com/album/con-todo-el-mundo',
  'https://flyinglotus.bandcamp.com/album/flamagra',
  'https://flyinglotus.bandcamp.com/album/until-the-quiet-comes',
  'https://flyinglotus.bandcamp.com/album/cosmogramma',
  'https://emancipator.bandcamp.com/album/seven-seas',
  'https://emancipator.bandcamp.com/album/safe-in-the-steep-cliffs',
  'https://cattledecapitation.bandcamp.com/album/the-anthropocene-extinction',
  'https://jpegmafia.bandcamp.com/album/veteran',
  'https://sunn.bandcamp.com/album/life-metal',
  'https://sunn.bandcamp.com/album/kannon',
  'https://chelseawolfe.bandcamp.com/album/she-reaches-out-to-she-reaches-out-to-she',
  'https://maxcooper.bandcamp.com/album/unspoken-words',
  'https://maxcooper.bandcamp.com/album/emergence',
  'https://beachhouse.bandcamp.com/album/bloom',
  'https://phoebebridgers.bandcamp.com/album/stranger-in-the-alps',
  'https://alvvays.bandcamp.com/album/antisocialites',
  'https://squarepusher.bandcamp.com/album/be-up-a-hello',
  'https://autechre.bandcamp.com/album/sign',
  'https://benfrost.bandcamp.com/album/the-centre-cannot-hold',
  'https://danielavery.bandcamp.com/album/drone-logic',
  'https://rossfromfriends.bandcamp.com/album/tread',
  'https://menitrust.bandcamp.com/album/headroom',
  'https://blackcountrynewroad.bandcamp.com/album/for-the-first-time',
  'https://blackcountrynewroad.bandcamp.com/album/ants-from-up-there',
  'https://squiduk.bandcamp.com/album/bright-green-field',
  'https://carolinepolachek.bandcamp.com/album/pang',
] as const;
