[phases.setup]
aptPkgs = ["python3", "python3-pip", "ffmpeg"]

[phases.install]
cmds = ["pip3 install yt-dlp", "bun install"]

[phases.build]
cmds = ["yt-dlp --version"]

[start]
cmd = "bun run start"
