import { Hono } from "hono";
import YTDlpWrap from "yt-dlp-wrap";
import path from "path";
import os from "os";
import {
  cookieArgsForYtdlp,
  buildYoutubeUpstreamFetchHeaders,
  ensureYoutubeCookiesFile,
} from "../lib/youtubeCookies";
import {
  getPoTokenForVideo,
  buildYoutubeExtractorArgs,
  isPoTokenProviderConfigured,
  getPoTokenProviderStatus,
  type PoTokenBundle,
} from "../lib/poTokenProvider";
import {
  getQuotaStats,
  getSearchCacheSize,
  purgeExpiredSearchCache,
  fetchNewReleases,
  fetchCuratedPlaylists,
  searchYouTube,
  getVideoInfoViaApi,
  getPlaylistTracksViaApi,
  isYouTubeApiAvailable,
  getYoutubeApiKeysDiagnostic,
  probeYoutubeApiKeys,
} from "../services/youtubeService";

const youtubeRouter = new Hono();

const VIDEO_ID_RE = /^[a-zA-Z0-9_-]{6,32}$/;
const YTDLP_BINARY_PATH = path.join(os.tmpdir(), "yt-dlp");
const ytDlp = new YTDlpWrap(YTDLP_BINARY_PATH);

/**
 * Browser User-Agent injected into every yt-dlp call.
 *
 * YouTube's anti-bot system fingerprints requests using UA + cookies + the
 * player_client. When we present the cookies of a real signed-in `web`
 * browser session, YouTube also expects a matching desktop Chrome UA. Sending
 * yt-dlp's default UA here is what triggers many of the
 * "Sign in to confirm you're not a bot" / "Requested format is not available"
 * failures we hit on the Railway egress IP.
 */
const YTDLP_BROWSER_UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

/** Common yt-dlp args for every call: browser UA + cert relaxation + cookies. */
function commonYtdlpArgs(): string[] {
  return [
    "--user-agent",
    YTDLP_BROWSER_UA,
    "--no-check-certificate",
    ...cookieArgsForYtdlp(),
  ];
}

/**
 * Same as `commonYtdlpArgs()` but WITHOUT cookies.
 *
 * EMPIRICAL FINDING (2026-04-19, /api/youtube/_test/:videoId A/B probes):
 * On Railway's egress IP, sending YouTube cookies causes the response to
 * contain ZERO playable audio formats — only storyboard images (sb0–sb3).
 * The same `ios` player_client request WITHOUT cookies returns m4a/webm
 * audio normally. The cookies are flagged as bot-suspicious server-side.
 *
 * So our default path is "no cookies + ios client". We only add cookies
 * back when we hit a hard failure that *might* be auth-gated (age/region).
 */
function noCookieYtdlpArgs(): string[] {
  return [
    "--user-agent",
    YTDLP_BROWSER_UA,
    "--no-check-certificate",
  ];
}

// Download the latest yt-dlp binary on every startup.
// yt-dlp ships anti-bot bypass updates almost weekly; pinning to whatever was
// already on /tmp means stale containers serve broken playback. Always pull
// the latest release on boot — costs ~3MB once per Railway container start.
(async () => {
  try {
    const fs = await import("fs");
    console.log("[yt-dlp] downloading latest standalone binary...");
    const url = "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux";
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const buf = await res.arrayBuffer();
    fs.writeFileSync(YTDLP_BINARY_PATH, Buffer.from(buf), { mode: 0o755 });
    console.log(
      `[yt-dlp] binary downloaded to ${YTDLP_BINARY_PATH} (${Math.round(buf.byteLength / 1024)}KB)`,
    );
  } catch (e: any) {
    console.error("[yt-dlp] startup error:", e.message);
  }
})();

// Cache resolved CDN URLs so repeated range requests don't re-run yt-dlp.
// IMPORTANT: YouTube CDN URLs carry a per-IP+per-client signature in the
// query string (`expire=…`, `pot=…`). Even though the `expire` claims ~6h,
// in practice these tokens stop being honored within ~30-90 minutes for
// no-PO-token clients, after which the CDN returns 403. So we cache only
// 30 minutes — long enough to keep range requests cheap, short enough that
// a stale URL doesn't block playback.
const urlCache = new Map<string, { url: string; expires: number }>();
const URL_TTL_MS = 30 * 60 * 1000;

function getCachedUrl(videoId: string): string | null {
  const entry = urlCache.get(videoId);
  if (entry && Date.now() < entry.expires) return entry.url;
  urlCache.delete(videoId);
  return null;
}

function setCachedUrl(videoId: string, url: string): void {
  urlCache.set(videoId, { url, expires: Date.now() + URL_TTL_MS });
}

function invalidateCachedUrl(videoId: string): void {
  urlCache.delete(videoId);
}

/** Match download route — YouTube blocks datacenter IPs on some clients only.
 *  Fast tier races in parallel (fastest wins, losers aborted).
 *  Slow tier is a sequential fallback if every fast client fails. */
/**
 * Player client racing tiers (2026 PO-token era).
 *
 * As of late-2025 YouTube changed its anti-bot pipeline:
 *  - `web` requires a Proof-of-Origin (PO) token generated by the browser; without
 *    it YouTube serves SABR-only formats yt-dlp can't access → "Requested format
 *    is not available".
 *  - `android` was deprecated client-side; YouTube responds with formats yt-dlp
 *    can no longer decode → same error.
 *  - `tv`, `tv_embedded`, and `ios` still work without a PO token.
 *
 * We race those three in parallel as the fast tier (with or without cookies),
 * and use `mweb` + `web_safari` as a slower fallback.
 *
 * The `formats=missing_pot` extractor-arg tells yt-dlp to NOT filter out
 * formats that lack a PO token — critical for `tv`/`ios`/`tv_embedded`.
 */
/**
 * Resolver attempt = (player_client, whether to attach cookies).
 *
 * 2026-04-19 PROBE FINDINGS — what actually returns a streaming URL:
 *
 *   1. ios/tv/tv_embedded + NO cookies → returns URL with MISSING POT.
 *      CDN serves bytes for older/un-flagged videos (e.g. Rick Astley)
 *      but 403s on currently popular tracks.
 *   2. mediaconnect/android_vr/ios_creator + NO cookies → lists formats
 *      but --get-url itself returns "Sign in to confirm you're not a bot".
 *   3. ANY client + cookies → only storyboards (current cookies flagged).
 *
 * So the best we can do today is option 1 with cookie-less ios/tv/tv_embedded.
 * For tracks where the CDN 403s, the user needs ONE of the following infra
 * fixes (none of which are pure-code):
 *   a) Fresh non-flagged YouTube cookies, OR
 *   b) bgutil-ytdlp-pot-provider plugin installed on Railway, OR
 *   c) Residential proxy (so YouTube doesn't see Railway's datacenter IP).
 */
type ResolveAttempt = { client: string; useCookies: boolean };
function getFastAttempts(): readonly ResolveAttempt[] {
  return [
    { client: "ios", useCookies: false },
    { client: "tv", useCookies: false },
    { client: "tv_embedded", useCookies: false },
  ] as const;
}
function getSlowAttempts(): readonly ResolveAttempt[] {
  return [
    { client: "mweb", useCookies: false },
    { client: "web_safari", useCookies: false },
    // Last resort for genuinely auth-gated content (age/region).
    { client: "ios", useCookies: true },
  ] as const;
}
const YTDLP_RESOLVE_FAST_TIMEOUT_MS = 10_000;
const YTDLP_RESOLVE_SLOW_TIMEOUT_MS = 15_000;

/** Run yt-dlp --get-url for a single player_client and return the CDN URL. */
function tryResolveWithClient(
  videoId: string,
  attempt: ResolveAttempt,
  timeoutMs: number,
  bundle: PoTokenBundle | null,
  externalSignal?: AbortSignal,
): { promise: Promise<string>; abort: () => void } {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  if (externalSignal) {
    if (externalSignal.aborted) controller.abort();
    else externalSignal.addEventListener("abort", () => controller.abort(), { once: true });
  }

  const baseArgs = attempt.useCookies ? commonYtdlpArgs() : noCookieYtdlpArgs();
  const extractorArgs = buildYoutubeExtractorArgs({
    client: attempt.client,
    bundle,
    includeMissingPot: true,
  });

  const promise = ytDlp
    .execPromise(
      [
        `https://www.youtube.com/watch?v=${videoId}`,
        "-f",
        // Bias to iOS-native m4a/aac first; keep loose fallbacks so we don't
        // hit "Requested format is not available" on weirder uploads.
        "bestaudio[ext=m4a]/bestaudio[acodec=aac]/bestaudio/best/bestaudio*/best*",
        "--get-url",
        "--no-playlist",
        "--no-warnings",
        "--quiet",
        "--socket-timeout",
        "8",
        "--extractor-args",
        extractorArgs,
        "--js-runtimes",
        "node",
        ...baseArgs,
      ],
      {},
      controller.signal,
    )
    .then((output) => {
      clearTimeout(timer);
      const url = output.trim().split("\n")[0]?.trim() ?? "";
      if (!url.startsWith("http")) throw new Error("yt-dlp returned non-URL output");
      return url;
    })
    .catch((e: any) => {
      clearTimeout(timer);
      throw new Error(e?.message ?? String(e));
    });

  return { promise, abort: () => controller.abort() };
}

/**
 * Resolve a YouTube videoId to a direct CDN audio URL using yt-dlp.
 * Phase 1: race the 3 most reliable clients in parallel (first URL wins,
 *          the other child processes are aborted immediately).
 * Phase 2: if every fast client fails, fall back to web/mweb sequentially.
 */
/**
 * Attempt list for the PO-token-enabled fast race.
 * `web` becomes viable when we have a PO token — that's the official
 * YouTube web player and gets the richest format set. We race it
 * alongside `ios` and `tv` for resilience.
 */
const PO_FAST_ATTEMPTS: readonly ResolveAttempt[] = [
  { client: "web", useCookies: false },
  { client: "ios", useCookies: false },
  { client: "tv", useCookies: false },
] as const;

async function resolveAudioUrl(videoId: string): Promise<string> {
  // Phase 0: try to mint a PO token. If the provider isn't configured
  // or the fetch fails, we fall through to the cookie-less ios/tv path
  // below — which still works for un-flagged tracks.
  const bundle = await getPoTokenForVideo(videoId);
  const fastAttempts = bundle ? PO_FAST_ATTEMPTS : getFastAttempts();
  const slowAttempts = getSlowAttempts();
  const labelOf = (a: ResolveAttempt) => {
    const tag = a.useCookies ? "+cookies" : "";
    const pot = bundle ? "+pot" : "";
    return `${a.client}${tag}${pot}`;
  };

  if (bundle) {
    console.log(`[yt-dlp] resolve ${videoId}: PO token acquired, racing web/ios/tv`);
  } else if (isPoTokenProviderConfigured()) {
    console.warn(`[yt-dlp] resolve ${videoId}: PO provider configured but token fetch failed → cookieless fallback`);
  }

  const races = fastAttempts.map((attempt) => {
    const { promise, abort } = tryResolveWithClient(
      videoId,
      attempt,
      YTDLP_RESOLVE_FAST_TIMEOUT_MS,
      bundle,
    );
    return {
      attempt,
      abort,
      promise: promise.then((url) => ({ attempt, url })),
    };
  });

  try {
    const winner = await Promise.any(races.map((r) => r.promise));
    for (const r of races) {
      if (r.attempt !== winner.attempt) r.abort();
    }
    if (winner.attempt !== fastAttempts[0]) {
      console.log(`[yt-dlp] resolve ${videoId}: fast-race won by ${labelOf(winner.attempt)}`);
    }
    return winner.url;
  } catch (e) {
    const fastErr = e instanceof AggregateError
      ? e.errors.map((er: any) => (er?.message ?? String(er)).split("\n")[0]).join(" | ")
      : String(e);
    console.warn(`[yt-dlp] resolve ${videoId}: fast tier exhausted — ${fastErr.slice(0, 240)}`);
  }

  let lastMsg = "";
  for (const attempt of slowAttempts) {
    try {
      const { promise } = tryResolveWithClient(
        videoId,
        attempt,
        YTDLP_RESOLVE_SLOW_TIMEOUT_MS,
        bundle,
      );
      const url = await promise;
      console.log(`[yt-dlp] resolve ${videoId}: slow fallback ok with ${labelOf(attempt)}`);
      return url;
    } catch (e: any) {
      lastMsg = e.message ?? String(e);
      console.warn(
        `[yt-dlp] resolve ${videoId} slow ${labelOf(attempt)}:`,
        lastMsg.split("\n")[0]?.slice(0, 160),
      );
    }
  }

  console.error("[yt-dlp] resolveAudioUrl exhausted all clients:", lastMsg.split("\n")[0]);
  throw new Error(`yt-dlp failed: ${lastMsg}`);
}

// Track in-flight resolutions so concurrent requests for the same video
// don't each spawn their own yt-dlp process
const inflight = new Map<string, Promise<string>>();

async function getAudioUrl(videoId: string): Promise<string> {
  const cached = getCachedUrl(videoId);
  if (cached) return cached;

  let pending = inflight.get(videoId);
  if (!pending) {
    pending = resolveAudioUrl(videoId).then((url) => {
      setCachedUrl(videoId, url);
      inflight.delete(videoId);
      return url;
    }).catch((e) => {
      inflight.delete(videoId);
      throw e;
    });
    inflight.set(videoId, pending);
  }
  return pending;
}

/**
 * GET /api/youtube/audio/:videoId
 * Resolves the YouTube video to a direct CDN URL via yt-dlp (cached for 4h),
 * then proxies the request — forwarding Range headers so iOS AVPlayer gets
 * proper 206 responses with Content-Length and Accept-Ranges.
 */
youtubeRouter.get("/audio/:videoId", async (c) => {
  const videoId = c.req.param("videoId");

  if (!videoId || !VIDEO_ID_RE.test(videoId)) {
    return c.json({ error: "Invalid YouTube video ID" }, 400);
  }

  const rangeHeader = c.req.header("Range");
  const MAX_AUDIO_PROXY_ATTEMPTS = 3;
  let upstream: Response | null = null;
  let lastDirectUrl = "";
  let lastError: string | null = null;

  for (let attempt = 0; attempt < MAX_AUDIO_PROXY_ATTEMPTS; attempt++) {
    if (attempt > 0) {
      urlCache.delete(videoId);
      ensureYoutubeCookiesFile();
      console.warn(`[YouTube] audio proxy retry ${attempt}/${MAX_AUDIO_PROXY_ATTEMPTS - 1} for ${videoId}`);
    }

    let directUrl: string;
    try {
      directUrl = await getAudioUrl(videoId);
      lastDirectUrl = directUrl;
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      lastError = msg;
      console.error("[YouTube] Failed to resolve CDN URL:", e);
      continue;
    }

    // If we have a PO token bundle for this video, forward visitor data
    // as X-Goog-Visitor-Id so the CDN ties the request to the same
    // identity that minted the token.
    const cachedBundle = await getPoTokenForVideo(videoId);
    const upstreamHeaders = buildYoutubeUpstreamFetchHeaders(directUrl, {
      rangeHeader,
      visitorData: cachedBundle?.visitorData,
    });
    const cdnAbort = new AbortController();
    const cdnTimeout = setTimeout(() => cdnAbort.abort(), 45_000);
    let res: Response;
    try {
      res = await fetch(directUrl, { headers: upstreamHeaders, signal: cdnAbort.signal });
    } catch (e: unknown) {
      clearTimeout(cdnTimeout);
      const msg = e instanceof Error ? e.message : String(e);
      lastError = msg;
      console.error("[YouTube] CDN fetch failed:", e);
      continue;
    }
    clearTimeout(cdnTimeout);

    upstream = res;
    if (res.ok) break;

    const retryable =
      res.status === 403 ||
      res.status === 404 ||
      res.status === 429 ||
      res.status === 502 ||
      res.status === 503;
    lastError = `HTTP ${res.status}`;
    if (!retryable) break;
  }

  if (!upstream || !upstream.ok) {
    console.error("[YouTube] audio proxy exhausted retries", {
      videoId,
      lastDirectUrl: lastDirectUrl ? `${lastDirectUrl.slice(0, 64)}…` : "",
      lastError,
    });
    return c.json({ error: lastError ?? "Failed to fetch audio from CDN" }, 502);
  }

  const contentType = upstream.headers.get("Content-Type") ?? "audio/mp4";

  if (!rangeHeader) {
    const responseHeaders: Record<string, string> = {
      "Content-Type": contentType,
      "Accept-Ranges": "bytes",
      "Cache-Control": "no-store",
      "Access-Control-Allow-Origin": "*",
    };
    const upstreamLength = upstream.headers.get("Content-Length");
    if (upstreamLength) responseHeaders["Content-Length"] = upstreamLength;
    return new Response(upstream.body, { status: 200, headers: responseHeaders });
  }

  const responseHeaders: Record<string, string> = {
    "Content-Type": contentType,
    "Cache-Control": "no-store",
    "Access-Control-Allow-Origin": "*",
  };

  const contentLength = upstream.headers.get("Content-Length");
  const contentRange = upstream.headers.get("Content-Range");
  const acceptRanges = upstream.headers.get("Accept-Ranges");

  if (contentLength) responseHeaders["Content-Length"] = contentLength;
  if (contentRange) responseHeaders["Content-Range"] = contentRange;
  if (acceptRanges) responseHeaders["Accept-Ranges"] = acceptRanges;

  return new Response(upstream.body, {
    status: upstream.status,
    headers: responseHeaders,
  });
});

/**
 * GET /api/youtube/download/:videoId
 * Downloads audio via yt-dlp to a temp file, then serves it to the mobile app.
 */
youtubeRouter.get("/download/:videoId", async (c) => {
  const videoId = c.req.param("videoId");
  if (!videoId || !VIDEO_ID_RE.test(videoId)) {
    return c.json({ error: "Invalid video ID" }, 400);
  }

  const tmpBase = `/tmp/yt_${videoId}_${Date.now()}`;
  const tmpTemplate = `${tmpBase}.%(ext)s`;

  // ios/tv/tv_embedded + NO cookies → returns formats; CDN serves bytes
  // for un-flagged videos. When a PO token is available we add `web` first
  // since it gets the richest format set with token-bound CDN access.
  const bundle = await getPoTokenForVideo(videoId);
  const PLAYER_CLIENTS = bundle
    ? (["web", "ios", "tv", "tv_embedded", "mweb"] as const)
    : (["ios", "tv", "tv_embedded", "mweb", "web_safari"] as const);
  if (bundle) {
    console.log(`[YouTube] download ${videoId}: PO token acquired`);
  }

  const tryClient = async (client: string): Promise<{ ok: true; path: string } | { ok: false; reason: string }> => {
    // Clean up any partial files from a previous attempt so the --print
    // output only reports the file this attempt created.
    Bun.spawn(["sh", "-c", `rm -f ${tmpBase}.* 2>/dev/null`]);

    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 60_000);
    try {
      const output = await ytDlp.execPromise([
        `https://www.youtube.com/watch?v=${videoId}`,
        "-f", "bestaudio[ext=m4a]/bestaudio[acodec=aac]/bestaudio/best/bestaudio*/best*",
        "--no-playlist",
        "-o", tmpTemplate,
        "--no-warnings",
        "--no-part",
        "--print", "after_move:filepath",
        "--extractor-args", buildYoutubeExtractorArgs({ client, bundle, includeMissingPot: true }),
        "--js-runtimes", "node",
        // Cookies are flagged as bot-suspicious on Railway IPs and cause
        // YouTube to return only storyboards. Download path skips them too.
        ...noCookieYtdlpArgs(),
      ], {}, controller.signal);
      clearTimeout(timer);
      const finalPath = output.trim().split("\n").pop()?.trim() ?? "";
      if (finalPath) return { ok: true, path: finalPath };
      return { ok: false, reason: "yt-dlp produced no output file" };
    } catch (e: any) {
      clearTimeout(timer);
      const msg: string = e.message ?? "";
      if (msg.includes("aborted")) return { ok: false, reason: "Download timed out" };
      const errLine = msg.split("\n").find((l: string) => l.includes("ERROR:")) ?? "";
      const reason = errLine.replace(/^ERROR:\s*\[youtube\]\s*[\w-]+:\s*/, "").trim() || msg.slice(0, 200);
      return { ok: false, reason };
    }
  };

  let result: { ok: true; path: string } | { ok: false; reason: string } = {
    ok: false,
    reason: "no player clients tried",
  };
  const attempts: string[] = [];
  for (const client of PLAYER_CLIENTS) {
    const attempt = await tryClient(client);
    if (attempt.ok) {
      result = attempt;
      if (attempts.length > 0) {
        console.log(`[YouTube] download ${videoId}: succeeded with ${client} after ${attempts.join(", ")} failed`);
      }
      break;
    }
    attempts.push(`${client} (${attempt.reason.slice(0, 60)})`);
    result = attempt;
    // Don't bother trying other clients for errors that are permanent
    // for this video (private / unavailable / copyright removed).
    const r = attempt.reason.toLowerCase();
    if (r.includes("private") || r.includes("copyright") || r.includes("removed") || r.includes("unavailable")) {
      break;
    }
  }

  // Final cleanup in case we bailed out mid-attempt.
  if (!result.ok) {
    Bun.spawn(["sh", "-c", `rm -f ${tmpBase}.* 2>/dev/null`]);
  }

  if (!result.ok) {
    console.error(`[YouTube] download failed for ${videoId} after trying ${attempts.length} clients: ${result.reason}`);
    const r = result.reason.toLowerCase();
    let userMsg = "This track couldn't be downloaded right now";
    if (r.includes("unavailable")) userMsg = "Video is unavailable";
    else if (r.includes("sign in") || r.includes("bot")) userMsg = "YouTube blocked this download — try again later";
    else if (r.includes("private")) userMsg = "This video is private";
    else if (r.includes("timed out")) userMsg = "Download timed out — try again";
    else if (r.includes("copyright") || r.includes("removed")) userMsg = "Video removed due to copyright";
    else if (r.includes("format") || r.includes("no video")) userMsg = "No compatible audio format found";
    return c.json({ error: userMsg }, 502);
  }

  try {
    const file = Bun.file(result.path);
    if (file.size === 0) throw new Error("Downloaded file is empty");

    const buffer = await file.arrayBuffer();
    Bun.spawn(["rm", "-f", result.path]);

    const ext = result.path.split(".").pop()?.toLowerCase() ?? "m4a";
    const contentType = ext === "mp3" ? "audio/mpeg" : "audio/mp4";

    console.log(`[YouTube] download ${videoId}: ${buffer.byteLength} bytes (${ext})`);

    return new Response(buffer, {
      status: 200,
      headers: {
        "Content-Type": contentType,
        "Content-Length": buffer.byteLength.toString(),
        "Content-Disposition": `attachment; filename="${videoId}.${ext}"`,
        "Accept-Ranges": "bytes",
        "Cache-Control": "no-store",
        "Access-Control-Allow-Origin": "*",
      },
    });
  } catch (e) {
    Bun.spawn(["rm", "-f", result.path]);
    console.error("[YouTube] serve error:", e instanceof Error ? e.message : e);
    return c.json({ error: "Download failed — please try again" }, 502);
  }
});

/**
 * GET /api/youtube/resolve/:videoId
 * Returns the direct CDN audio URL for use in downloads.
 */
youtubeRouter.get("/resolve/:videoId", async (c) => {
  const videoId = c.req.param("videoId");
  if (!videoId || !VIDEO_ID_RE.test(videoId)) {
    return c.json({ error: "Invalid video ID" }, 400);
  }
  // ?fresh=1 busts the cache — used by mobile when a previously-cached
  // CDN URL just 403'd (signature/PO token expired client-side).
  if (c.req.query("fresh") === "1") {
    invalidateCachedUrl(videoId);
  }
  try {
    const url = await getAudioUrl(videoId);
    return c.json({ data: { url } });
  } catch (e) {
    return c.json({ error: "Failed to resolve audio URL" }, 502);
  }
});

/**
 * GET /api/youtube/warm/:videoId
 * Pre-resolves and caches the CDN URL for a video so subsequent /audio requests are instant.
 */
youtubeRouter.get("/warm/:videoId", async (c) => {
  const videoId = c.req.param("videoId");
  if (!videoId || !VIDEO_ID_RE.test(videoId)) {
    return c.json({ error: "Invalid video ID" }, 400);
  }
  const already = !!getCachedUrl(videoId);
  if (!already) {
    getAudioUrl(videoId).catch(() => {});
  }
  return c.json({ data: { cached: already, warming: !already } });
});

/**
 * GET /api/youtube/search?q=...&maxResults=10
 */
youtubeRouter.get("/search", async (c) => {
  const q = c.req.query("q")?.trim();
  const maxResults = Math.min(parseInt(c.req.query("maxResults") ?? "10", 10), 20);
  if (!q) return c.json({ error: "Missing q parameter" }, 400);

  try {
    const ytdlpResults = await searchYouTubeYtDlp(q, maxResults);
    if (ytdlpResults.length > 0) return c.json({ data: ytdlpResults });
  } catch (e) {
    console.error("[YouTube] yt-dlp search failed:", e);
  }

  try {
    const apiResults = await searchYouTube(q, maxResults);
    return c.json({ data: apiResults });
  } catch {
    return c.json({ data: [] });
  }
});

/** ytsearch on Railway needs cookies + rotating clients; otherwise we fall through to Data API and burn invalid keys. */
const YTDLP_SEARCH_CLIENTS = ["tv", "tv_embedded", "ios", "mweb"] as const;

function parseYtsearchJsonLines(
  output: string,
  maxResults: number,
  searchQuery: string,
): Array<{
  videoId: string;
  title: string;
  channelName: string;
  thumbnailUrl: string;
  publishedAt: string;
  searchQuery: string;
}> {
  return output
    .trim()
    .split("\n")
    .filter((l) => l.trim())
    .flatMap((line) => {
      try {
        const j = JSON.parse(line) as Record<string, unknown>;
        let videoId = typeof j.id === "string" ? j.id : "";
        if (!videoId && typeof j.url === "string") {
          const m = j.url.match(/[?&]v=([a-zA-Z0-9_-]{11})/);
          if (m) videoId = m[1];
        }
        if (!videoId || !/^[a-zA-Z0-9_-]{6,32}$/.test(videoId)) return [];
        const duration = typeof j.duration === "number" ? j.duration : 0;
        if (duration > 480) return [];
        return [
          {
            videoId,
            title: String(j.title ?? ""),
            channelName: String(j.uploader ?? j.channel ?? j.uploader_id ?? ""),
            thumbnailUrl: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
            publishedAt: "",
            searchQuery,
          },
        ];
      } catch {
        return [];
      }
    })
    .slice(0, maxResults);
}

async function searchYouTubeYtDlp(query: string, maxResults: number): Promise<Array<{
  videoId: string; title: string; channelName: string; thumbnailUrl: string; publishedAt: string; searchQuery: string;
}>> {
  const safeQuery = query.replace(/[\r\n\0]/g, " ").trim().slice(0, 200);
  if (!safeQuery) return [];

  const fetchCount = Math.min(Math.max(maxResults * 3, 15), 50);
  let lastErr = "";

  for (const client of YTDLP_SEARCH_CLIENTS) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 45_000);
    try {
      const output = await ytDlp.execPromise(
        [
          `ytsearch${fetchCount}:${safeQuery}`,
          "--dump-json",
          "--flat-playlist",
          "--quiet",
          "--no-warnings",
          "--extractor-args",
          `youtube:player_client=${client};formats=missing_pot`,
          "--js-runtimes",
          "node",
          ...noCookieYtdlpArgs(),
        ],
        {},
        controller.signal,
      );
      clearTimeout(timer);
      const rows = parseYtsearchJsonLines(output, maxResults, safeQuery);
      if (rows.length > 0) {
        if (client !== YTDLP_SEARCH_CLIENTS[0]) {
          console.log(`[yt-dlp] search "${safeQuery.slice(0, 40)}…" ok with player_client=${client} (${rows.length} results)`);
        }
        return rows;
      }
    } catch (e: any) {
      clearTimeout(timer);
      lastErr = e.message ?? String(e);
      console.warn(
        `[yt-dlp] search client=${client}:`,
        lastErr.split("\n")[0]?.slice(0, 160),
      );
    }
  }

  if (lastErr) console.error("[yt-dlp] search exhausted all clients:", lastErr.split("\n")[0]?.slice(0, 200));
  return [];
}

/**
 * GET /api/youtube/info/:videoId
 */
youtubeRouter.get("/info/:videoId", async (c) => {
  const videoId = c.req.param("videoId");
  if (!videoId || !VIDEO_ID_RE.test(videoId)) {
    return c.json({ error: "Invalid YouTube video ID" }, 400);
  }

  // 1. Prefer the YouTube Data API — it's not subject to the bot-detection
  //    challenge that yt-dlp hits on datacenter IPs.
  if (isYouTubeApiAvailable()) {
    const apiInfo = await getVideoInfoViaApi(videoId);
    if (apiInfo) return c.json({ data: apiInfo });
    console.warn("[YouTube] API fallback — video not found or API unavailable, trying yt-dlp");
  }

  // 2. Fall back to yt-dlp, trying multiple player clients since YouTube
  //    blocks some of them with "Sign in to confirm you're not a bot".
  try {
    const info = await getVideoInfo(videoId);
    return c.json({ data: info });
  } catch (e) {
    console.error("[YouTube] info error:", e);
    const msg = e instanceof Error ? e.message : "Failed to get video info";
    return c.json({ error: msg }, 502);
  }
});

const YT_DLP_CLIENT_FALLBACKS = [
  "tv",
  "ios",
  "tv_embedded",
  "web_safari",
  "mweb",
];

async function getVideoInfo(videoId: string): Promise<{ title: string; channel: string; thumbnail: string; duration: number }> {
  const baseArgs = [
    `https://www.youtube.com/watch?v=${videoId}`,
    "--print", "%(title)s",
    "--print", "%(uploader)s",
    "--print", "%(thumbnail)s",
    "--print", "%(duration)s",
    "--no-playlist",
    "--quiet",
    "--no-warnings",
  ];

  const bundle = await getPoTokenForVideo(videoId);
  const clients = bundle
    ? (["web", ...YT_DLP_CLIENT_FALLBACKS] as const)
    : YT_DLP_CLIENT_FALLBACKS;

  let lastError: Error | null = null;
  for (const client of clients) {
    try {
      const output = await ytDlp.execPromise([
        ...baseArgs,
        "--extractor-args", buildYoutubeExtractorArgs({ client, bundle, includeMissingPot: true }),
        ...noCookieYtdlpArgs(),
      ]);
      const lines = output.trim().split("\n");
      if (lines.length < 3) throw new Error(`yt-dlp info returned insufficient output`);
      return {
        title: lines[0] ?? "Unknown Title",
        channel: lines[1] ?? "Unknown Artist",
        thumbnail: lines[2] ?? `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`,
        duration: parseInt(lines[3] ?? "0") || 0,
      };
    } catch (e) {
      lastError = e instanceof Error ? e : new Error(String(e));
      console.warn(`[yt-dlp] info client=${client} failed:`, lastError.message.split("\n")[0]);
    }
  }
  throw lastError ?? new Error("yt-dlp info failed for all player clients");
}

/** List-view row: minimal fields for clients (id + playback URL). */
function toPlaylistTrackSlim(t: {
  videoId: string;
  title: string;
  channel: string;
  thumbnail: string;
  duration: number;
}) {
  const id = t.videoId;
  return {
    id,
    title: t.title,
    artist: t.channel,
    artwork: t.thumbnail,
    url: `https://www.youtube.com/watch?v=${encodeURIComponent(id)}`,
    duration: Math.floor(Number(t.duration)) || 0,
  };
}

/**
 * GET /api/youtube/playlist-tracks?listId=
 */
youtubeRouter.get("/playlist-tracks", async (c) => {
  const listId = c.req.query("listId")?.trim();
  if (!listId || !/^[a-zA-Z0-9_-]+$/.test(listId)) {
    return c.json({ error: "Invalid playlist ID" }, 400);
  }

  const cacheHeaders = () => {
    c.header("Cache-Control", "public, max-age=3600, stale-while-revalidate=86400");
  };

  // 1. Prefer the YouTube Data API v3.
  if (isYouTubeApiAvailable()) {
    const apiTracks = await getPlaylistTracksViaApi(listId);
    if (apiTracks && apiTracks.length > 0) {
      cacheHeaders();
      return c.json({ data: apiTracks.map(toPlaylistTrackSlim) });
    }
    console.warn("[YouTube] API playlist fallback — empty or unavailable, trying yt-dlp");
  }

  // 2. Fall back to yt-dlp.
  try {
    const tracks = await getPlaylistTracks(listId);
    cacheHeaders();
    return c.json({ data: tracks.map(toPlaylistTrackSlim) });
  } catch (e) {
    console.error("[YouTube] playlist-tracks error:", e);
    const msg = e instanceof Error ? e.message : "Failed to fetch playlist";
    return c.json({ error: msg }, 502);
  }
});

async function getPlaylistTracks(listId: string): Promise<Array<{ videoId: string; title: string; channel: string; thumbnail: string; duration: number }>> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 60_000);
  let output: string;
  try {
    output = await ytDlp.execPromise([
      `https://music.youtube.com/playlist?list=${listId}`,
      "--flat-playlist",
      "--dump-json",
      "--no-warnings",
      "--quiet",
      ...commonYtdlpArgs(),
    ], {}, controller.signal);
    clearTimeout(timer);
  } catch (e: any) {
    clearTimeout(timer);
    throw new Error(`yt-dlp playlist failed: ${e.message}`);
  }
  return output
    .trim()
    .split("\n")
    .filter((line) => line.trim())
    .map((line) => {
      try {
        const j = JSON.parse(line);
        const id: string = j.id ?? "";
        if (!id) return null;
        const thumbnails: Array<{ url: string }> = j.thumbnails ?? [];
        const thumb =
          thumbnails.length > 0
            ? thumbnails[thumbnails.length - 1].url
            : `https://img.youtube.com/vi/${id}/hqdefault.jpg`;
        return {
          videoId: id,
          title: (j.title as string) ?? "Unknown",
          channel: (j.channel ?? j.uploader ?? "Unknown") as string,
          thumbnail: thumb,
          duration: (j.duration as number) ?? 0,
        };
      } catch {
        return null;
      }
    })
    .filter((t): t is NonNullable<typeof t> => t !== null);
}

youtubeRouter.get("/new-releases", async (c) => {
  const maxResults = Math.min(parseInt(c.req.query("maxResults") ?? "20", 10), 50);
  const results = await fetchNewReleases(maxResults);
  return c.json({ data: results });
});

youtubeRouter.get("/playlists", async (c) => {
  const results = await fetchCuratedPlaylists();
  return c.json({ data: results });
});

/** Raw yt-dlp single-shot test. Returns stdout/stderr for one client so we can
 *  see exactly what YouTube is rejecting (useful when the racer's error
 *  capture loses the actual message). Visit:
 *  /api/youtube/_test/dQw4w9WgXcQ?client=tv */
youtubeRouter.get("/_test/:videoId", async (c) => {
  const videoId = c.req.param("videoId");
  if (!videoId || !VIDEO_ID_RE.test(videoId)) {
    return c.json({ error: "Invalid video ID" }, 400);
  }
  const client = c.req.query("client") ?? "tv";
  const fmt = c.req.query("fmt") ?? "bestaudio[ext=m4a]/bestaudio[acodec=aac]/bestaudio/best/bestaudio*/best*";
  const listFormats = c.req.query("listFormats") === "1";

  const noCookies = c.req.query("noCookies") === "1";
  const baseArgs = noCookies ? [
    "--user-agent",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "--no-check-certificate",
  ] : commonYtdlpArgs();

  const args = [
    `https://www.youtube.com/watch?v=${videoId}`,
    "-f", fmt,
    listFormats ? "--list-formats" : "--get-url",
    "--no-playlist",
    "--no-warnings",
    "--socket-timeout", "8",
    "--extractor-args", `youtube:player_client=${client};formats=missing_pot`,
    ...baseArgs,
  ];

  const startedAt = Date.now();
  const proc = Bun.spawn(["/tmp/yt-dlp", ...args], {
    stdout: "pipe",
    stderr: "pipe",
  });
  const [stdout, stderr] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
  ]);
  await proc.exited;
  const elapsedMs = Date.now() - startedAt;

  return c.json({
    videoId,
    client,
    fmt,
    listFormats,
    elapsedMs,
    exitCode: proc.exitCode,
    stdout: stdout.slice(0, 6000),
    stderr: stderr.slice(0, 6000),
    cookies: noCookies ? "skipped (noCookies=1)" : (cookieArgsForYtdlp().length > 0 ? "applied" : "missing"),
  });
});

youtubeRouter.get("/_diag", async (c) => {
  const fs = await import("fs");
  const { YTDLP_COOKIES_PATH } = await import("../lib/youtubeCookies");

  const rawEnv = (process.env.YOUTUBE_COOKIES ?? process.env.YOUTUBE_COOKIES_BASE64 ?? "").trim();
  const envVarUsed = process.env.YOUTUBE_COOKIES
    ? "YOUTUBE_COOKIES"
    : process.env.YOUTUBE_COOKIES_BASE64
      ? "YOUTUBE_COOKIES_BASE64"
      : null;

  const envSet = rawEnv.length > 0;
  const envLength = rawEnv.length;
  const envFirst40 = envSet ? rawEnv.slice(0, 40) : null;

  const looksLikeRawCookies =
    envSet &&
    (rawEnv.startsWith("# Netscape") ||
      rawEnv.startsWith("#HttpOnly_") ||
      rawEnv.startsWith(".youtube.com") ||
      rawEnv.includes("\t"));

  let decodeOk = false;
  let decodedPreview: string | null = null;
  let decodeError: string | null = null;
  let decodedLineCount = 0;
  let cookieCount = 0;

  if (envSet) {
    try {
      const decoded = Buffer.from(rawEnv, "base64").toString("utf-8");
      decodedPreview = decoded.slice(0, 80);
      decodedLineCount = decoded.split("\n").length;
      cookieCount = decoded
        .split("\n")
        .filter((l) => {
          const t = l.trim();
          if (!t || t.startsWith("#")) return false;
          return t.split("\t").length >= 7;
        }).length;
      decodeOk =
        decoded.startsWith("# Netscape") ||
        decoded.startsWith("#HttpOnly_") ||
        decoded.startsWith(".youtube.com") ||
        cookieCount > 0;
    } catch (e) {
      decodeError = e instanceof Error ? e.message : String(e);
    }
  }

  const wroteFile = ensureYoutubeCookiesFile();
  let fileExists = false;
  let fileBytes = 0;
  try {
    fileExists = fs.existsSync(YTDLP_COOKIES_PATH);
    if (fileExists) fileBytes = fs.statSync(YTDLP_COOKIES_PATH).size;
  } catch {
    fileExists = false;
  }

  const ytDlpBinaryExists = fs.existsSync(YTDLP_BINARY_PATH);

  const verdict =
    !envSet
      ? "MISSING_ENV — set YOUTUBE_COOKIES to base64 of cookies.txt"
      : looksLikeRawCookies
        ? "RAW_NOT_BASE64 — value looks like raw cookies.txt; encode with `base64 -i cookies.txt`"
        : !decodeOk
          ? "DECODE_BAD — base64 decoded but result is not a valid cookies file"
          : !wroteFile
            ? "WRITE_FAILED — could not write /tmp/youtube-cookies.txt"
            : cookieCount === 0
              ? "EMPTY_AFTER_DECODE — file written but no cookie rows parsed"
              : "OK";

  return c.json({
    verdict,
    envVarUsed,
    env: {
      set: envSet,
      length: envLength,
      first40: envFirst40,
      looksLikeRawCookies,
    },
    decode: {
      ok: decodeOk,
      preview: decodedPreview,
      error: decodeError,
      lineCount: decodedLineCount,
      cookieRowCount: cookieCount,
    },
    file: {
      path: YTDLP_COOKIES_PATH,
      exists: fileExists,
      bytes: fileBytes,
      ensureWroteOk: wroteFile,
    },
    ytDlp: {
      binaryPath: YTDLP_BINARY_PATH,
      binaryExists: ytDlpBinaryExists,
    },
    poToken: getPoTokenProviderStatus(),
  });
});

/**
 * GET /api/youtube/_pot/:videoId
 * Probe the configured PO token provider for a single videoId.
 * Returns token+visitor metadata so we can verify the provider is reachable.
 * Never logs the raw token.
 */
youtubeRouter.get("/_pot/:videoId", async (c) => {
  const videoId = c.req.param("videoId");
  if (!videoId || !VIDEO_ID_RE.test(videoId)) {
    return c.json({ error: "Invalid videoId" }, 400);
  }
  const status = getPoTokenProviderStatus();
  if (!status.configured) {
    return c.json({ ok: false, reason: "POT_PROVIDER_URL not configured", status });
  }
  const start = Date.now();
  const bundle = await getPoTokenForVideo(videoId);
  const elapsedMs = Date.now() - start;
  if (!bundle) {
    return c.json({ ok: false, reason: "provider returned null", elapsedMs, status });
  }
  return c.json({
    ok: true,
    elapsedMs,
    poTokenLength: bundle.poToken.length,
    poTokenPreview: `${bundle.poToken.slice(0, 8)}…${bundle.poToken.slice(-4)}`,
    visitorDataLength: bundle.visitorData?.length ?? 0,
    expiresAt: new Date(bundle.expiresAt).toISOString(),
    status,
  });
});

/**
 * GET /api/youtube/_keys
 * Diagnostic for YOUTUBE_API_KEY_* env vars. Shows which slots are populated,
 * length, and a masked preview ("AIza…XYZ4"). Add `?probe=1` to actually call
 * Google with each key (1 quota unit each) and report the real failure reason
 * (API_KEY_INVALID / ipRefererBlocked / accessNotConfigured / etc).
 */
youtubeRouter.get("/_keys", async (c) => {
  const diag = getYoutubeApiKeysDiagnostic();
  const probe = c.req.query("probe") === "1";
  const probeResults = probe ? await probeYoutubeApiKeys() : null;
  return c.json({
    diag,
    probe: probeResults,
    notes: {
      whatLooksValid:
        "A valid Google API key matches /^AIza[0-9A-Za-z_-]{35}$/ — exactly 39 chars starting with 'AIza'.",
      commonCauses: [
        "Key was copy-pasted with leading/trailing whitespace or a newline",
        "Key belongs to a Google Cloud project that was deleted/suspended",
        "YouTube Data API v3 is NOT enabled on the key's project (Console → APIs & Services → Library)",
        "Key has 'HTTP referrer' restrictions — Railway server-side calls don't send a referrer, so it'll always reject",
        "Key has 'IP address' restrictions and Railway's egress IP isn't allow-listed",
      ],
    },
  });
});

youtubeRouter.get("/quota", (c) => {
  const stats = getQuotaStats();
  const cacheSize = getSearchCacheSize();
  const purged = purgeExpiredSearchCache();
  return c.json({
    data: {
      quota: {
        activeKey: `${stats.keyIndex}/${stats.totalKeys}`,
        unitsUsedToday: stats.totalUnits,
        dailyLimit: 10000,
        percentUsed: ((stats.totalUnits / 10000) * 100).toFixed(1) + '%',
        apiCallsToday: stats.callCount,
        cacheHitsToday: stats.cacheHits,
        unitsSavedByCache: stats.cacheHits * 100,
        resetsAt: new Date(stats.resetAt).toISOString(),
      },
      cache: {
        entriesActive: cacheSize - purged,
        entriesPurged: purged,
        ttlHours: 24,
      },
    },
  });
});

export { youtubeRouter };
